// Writes public/licenses/THIRD_PARTY.txt: the name, version, licence and full licence text of every third-party
// package the extension's bundles contain. The bundles decide, not package.json: the extension is built once with
// source maps into a temporary directory, and every node_modules package a map names is listed.
//   pnpm notices   (`pnpm licenses` is a pnpm command of its own)
import { existsSync, mkdtempSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { build } from 'wxt'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const OUT = join(ROOT, 'public/licenses/THIRD_PARTY.txt')
/** Packages published without a licence file: the licence file of the repository they are published from */
const REPOSITORY_LICENSE = {
  wxt: 'scripts/licenses/wxt-dev.LICENSE',
  '@wxt-dev/browser': 'scripts/licenses/wxt-dev.LICENSE',
  '@wxt-dev/storage': 'scripts/licenses/wxt-dev.LICENSE',
}
const LICENSE_FILE = /^(licen[cs]e|copying)(\.(md|txt))?$/i
const NOTICE_FILE = /^notice(\.(md|txt))?$/i

const tmp = mkdtempSync(join(tmpdir(), 'jevpaper-licenses-'))
try {
  await build({ root: ROOT, outDir: tmp, logLevel: 'warn', vite: () => ({ build: { sourcemap: true } }) })
  const maps = []
  const walk = dir => {
    for (const name of readdirSync(dir)) {
      const path = join(dir, name)
      if (statSync(path).isDirectory()) walk(path)
      else if (name.endsWith('.map')) maps.push(path)
    }
  }
  walk(tmp)
  if (!maps.length) throw new Error('the build wrote no source maps')

  /** Package directory → the bundles that contain it */
  const packages = new Map()
  for (const map of maps) {
    const { sources, sourceRoot = '' } = JSON.parse(readFileSync(map, 'utf8'))
    for (const source of sources) {
      const at = source.lastIndexOf('node_modules/')
      if (at < 0) continue
      const parts = source.slice(at + 'node_modules/'.length).split('/')
      const name = parts[0].startsWith('@') ? `${parts[0]}/${parts[1]}` : parts[0]
      const dir = resolve(dirname(map), sourceRoot, source.slice(0, at + 'node_modules/'.length) + name)
      if (!packages.has(dir)) packages.set(dir, new Set())
      // Without the content hash in a chunk's name, so the file changes only when the packages do
      packages.get(dir).add(map.slice(tmp.length + 1).replace(/^chrome-mv3\//, '').replace(/\.map$/, '').replace(/-[\w-]{8}\.js$/, '.js'))
    }
  }

  const entries = [...packages].map(([dir, bundles]) => {
    const pkg = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8'))
    const files = readdirSync(dir)
    const licenseFiles = files.filter(f => LICENSE_FILE.test(f)).map(f => join(dir, f))
    if (!licenseFiles.length && REPOSITORY_LICENSE[pkg.name]) licenseFiles.push(join(ROOT, REPOSITORY_LICENSE[pkg.name]))
    if (!licenseFiles.length) throw new Error(`${pkg.name}@${pkg.version} has no licence file: add its repository's to REPOSITORY_LICENSE`)
    const notices = files.filter(f => NOTICE_FILE.test(f)).map(f => join(dir, f))
    const license = typeof pkg.license === 'string' ? pkg.license : (pkg.license?.type ?? 'see the text below')
    return { name: pkg.name, version: pkg.version, license, bundles: [...bundles].sort(), texts: [...licenseFiles, ...notices].map(f => readFileSync(f, 'utf8').trim()) }
  })
  entries.sort((a, b) => a.name.localeCompare(b.name))

  const rule = '='.repeat(80)
  const out = [
    'JevPaper bundles the third-party packages below. Each keeps its own licence, reproduced in full after its name.',
    'JevPaper itself is licensed under GPL-3.0 (LICENSE); the Lucide icon is under ISC (lucide.txt).',
    'Generated by scripts/licenses.mjs (pnpm notices) from the bundles themselves; do not edit by hand.',
    '',
    ...entries.map(e => `- ${e.name} ${e.version} (${e.license})`),
    '',
    ...entries.flatMap(e => [rule, `${e.name} ${e.version}`, `License: ${e.license}`, `In: ${e.bundles.join(', ')}`, rule, '', ...e.texts.flatMap(t => [t, '']), '']),
  ]
  writeFileSync(OUT, `${out.join('\n').trimEnd()}\n`)
  console.log(`${OUT.slice(ROOT.length + 1)}: ${entries.map(e => `${e.name}@${e.version}`).join(', ')}`)
} finally {
  if (existsSync(tmp)) rmSync(tmp, { recursive: true, force: true })
}
